# Render Blueprint - SibelGPT Projesi için
# Sadece Web Servisini (Backend API) yönetir.
# Starter Plan ve Frankfurt bölgesindedir.

services:
  # --- 1. Mevcut Web Servisi (SibelGPT Backend API) ---
  - type: web
    name: sibelgpt-backend        # Mevcut web servisinin adı
    env: python
    region: frankfurt             # Bölge (Frankfurt olarak ayarlandı)
    plan: starter                 # Plan (Starter olarak ayarlandı)
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000 # Web servisinin başlatma komutu
    envVars:
      - key: OPENAI_API_KEY         # Backend sadece bunu kullanıyor
        sync: false                 # Değeri Render dashboard'dan alır
