# Render Blueprint - SibelGPT Projesi için
# Sadece Web Servisini (Backend API) yönetir.
# Starter Plan ve Frankfurt bölgesindedir.

services:
  # --- 1. Mevcut Web Servisi (SibelGPT Backend API) ---
  - type: web
    name: sibelgpt-backend        # Mevcut web servisinin adı
    env: python
    pythonVersion: "3.11"         # PYTHON VERSİYONU EKLENDİ
    region: frankfurt             # Bölge (Frankfurt olarak ayarlandı)
    plan: starter                 # Plan (Starter olarak ayarlandı)
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000 # Web servisinin başlatma komutu
    envVars:
      - key: OPENAI_API_KEY         # OpenAI için
        sync: false                 # Değeri Render dashboard'dan alır
      - key: SUPABASE_URL           # Supabase URL'si için
        sync: false                 # Değeri Render dashboard'dan alır
      - key: SUPABASE_KEY           # Supabase anahtarı için
        sync: false                 # Değeri Render dashboard'dan alır
      - key: GOOGLE_API_KEY         # Google API Anahtarı için (YENİ)
        sync: false                 # Değeri Render dashboard'dan alır
      - key: GOOGLE_CSE_ID          # Google Custom Search Engine ID (YENİ)
        value: d352129b3656e4b4f # Varsayılan değer (cx= kaldırıldı)
